-- ============================================================================
--  Veil — v3 migration
--  Adds: per-user invite password gate + per-user runtime settings overrides
--  Idempotent. Run after v2.sql.
-- ============================================================================

-- Per-token password gate. The hash is PBKDF2-SHA-256 formatted as
-- `pbkdf2$<iter>$<salt-b64url>$<hash-b64url>` and is generated by the app,
-- never by the database. Nullable to keep backwards compatibility with
-- existing rows.
alter table public.invite_tokens
  add column if not exists gate_password_hash text;

-- Per-user settings overrides. Each key, when present, overrides the
-- corresponding app_settings value for that user only. Stored as jsonb so the
-- shape can evolve without further migrations.
alter table public.profiles
  add column if not exists settings jsonb not null default '{}'::jsonb;
